version: '3'

services:
  nano-node-api:
    image: nanocurrency/nano-test
    ports:
      - "17076:17076"
      - "17078:17078"
    restart: always
    volumes:
      - NanoTest:/root  # TODO: harden this

volumes:
  NanoTest:
